name: gps_reporter
description: Aplicación para enviar coordenadas GPS

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Dependencias para GPS y HTTP
  geolocator: ^14.0.2          # Para obtener ubicación GPS
  permission_handler: ^12.0.1  # Para manejar permisos
  http: ^1.1.0                 # Para peticiones HTTP
  intl: ^0.20.2               # Para formatear fechas
  image_picker: ^1.2.0      # Para seleccionar o tomar fotos
  flutter_image_compress: ^2.4.0 # Para comprimir imágenes antes de convertir a base64
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true